#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ManyDiet.AndroidView.Resource", IsApplication=true)]

namespace ManyDiet.AndroidView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::ManyDiet.AndroidView.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::ManyDiet.AndroidView.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060018
			public const int addBurned = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int addBurnedQuick = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int addEaten = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int addEatenQuick = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int addPlan = 2131099678;
			
			// aapt resource value: 0x7f060015
			public const int burn = 2131099669;
			
			// aapt resource value: 0x7f060006
			public const int burnitemdatetime = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int burnitemname = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int burnitemtrack = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int burnlist = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int burnlisttitlename = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int burnlisttitletrack = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int burnpage = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int dietitemdatetime = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int dietitemmetric = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int dietitemname = 2131099658;
			
			// aapt resource value: 0x7f060012
			public const int eatitemdatetime = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int eatitemname = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int eatitemtrack = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int eatlist = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int eatlisttitlename = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int eatlisttitletrack = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int eatpage = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int flb = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int flbBurn = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int frameLayout1 = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int frameLayout1burn = 2131099649;
			
			// aapt resource value: 0x7f060016
			public const int planlist = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int removeBurnEntry = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int removeEatEntry = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int removePlanEntry = 2131099677;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Burn = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BurnEntryLine = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DietInstanceLine = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Eat = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EatEntryLine = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Plan = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int BurnEntryMenu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int BurnMenu = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int EatEntryMenu = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int EatMenu = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int PlanEntryMenu = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int PlanMenu = 2131034117;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int burn = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int eat = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int plan = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
