#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Consonance.Resource", IsApplication=true)]

namespace Consonance
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Consonance.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Consonance.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int norm = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int pres = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int sel = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int DietInstanceLineSelector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070028
			public const int addBurned = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int addBurnedQuick = 2131165225;
			
			// aapt resource value: 0x7f07002b
			public const int addEaten = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int addEatenQuick = 2131165228;
			
			// aapt resource value: 0x7f07002e
			public const int addPlan = 2131165230;
			
			// aapt resource value: 0x7f070006
			public const int burnTrackText = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int burnitemdatetime = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int burnitemname = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int burnitemtrack = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int burnlist = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int burnlisttitlename = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int burnlisttitletrack = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int burnpage = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int dietitemdatetime = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int dietitemmetric = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int dietitemname = 2131165195;
			
			// aapt resource value: 0x7f070013
			public const int eatTrackText = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int eatitemdatetime = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int eatitemname = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int eatitemtrack = 2131165206;
			
			// aapt resource value: 0x7f070012
			public const int eatlist = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int eatlisttitlename = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int eatlisttitletrack = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int eatpage = 2131165197;
			
			// aapt resource value: 0x7f070025
			public const int flb = 2131165221;
			
			// aapt resource value: 0x7f070002
			public const int flbBurn = 2131165186;
			
			// aapt resource value: 0x7f07000f
			public const int flpEat = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int frameLayout1 = 2131165198;
			
			// aapt resource value: 0x7f070001
			public const int frameLayout1burn = 2131165185;
			
			// aapt resource value: 0x7f07001a
			public const int getvalues = 2131165210;
			
			// aapt resource value: 0x7f070023
			public const int getvalues_cancel = 2131165219;
			
			// aapt resource value: 0x7f07001e
			public const int getvalues_date = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int getvalues_datepicker = 2131165215;
			
			// aapt resource value: 0x7f070017
			public const int getvalues_item = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int getvalues_itemtitle = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int getvalues_itemvalue = 2131165209;
			
			// aapt resource value: 0x7f070021
			public const int getvalues_ok = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int getvalues_scrolllinearlayout = 2131165218;
			
			// aapt resource value: 0x7f07001c
			public const int getvalues_titlebox = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int getvalues_titleboxname = 2131165213;
			
			// aapt resource value: 0x7f07001b
			public const int getvalues_titletext = 2131165211;
			
			// aapt resource value: 0x7f070020
			public const int getvalues_valuesscroller = 2131165216;
			
			// aapt resource value: 0x7f070024
			public const int plan = 2131165220;
			
			// aapt resource value: 0x7f070026
			public const int planlist = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int removeBurnEntry = 2131165223;
			
			// aapt resource value: 0x7f07002a
			public const int removeEatEntry = 2131165226;
			
			// aapt resource value: 0x7f07002d
			public const int removePlanEntry = 2131165229;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Burn = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BurnEntryLine = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DietInstanceLine = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Eat = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EatEntryLine = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int GetValueRow = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int GetValues = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Plan = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int BurnEntryMenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int BurnMenu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int EatEntryMenu = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int EatMenu = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int PlanEntryMenu = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int PlanMenu = 2131099653;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int ApplicationName = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int Hello = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int burn = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int eat = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int plan = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
