#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Consonance.Resource", IsApplication=true)]

namespace Consonance
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Consonance.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Consonance.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int norm = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int pres = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int sel = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int DietInstanceLineSelector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001d
			public const int add = 2131230749;
			
			// aapt resource value: 0x7f080024
			public const int addBurned = 2131230756;
			
			// aapt resource value: 0x7f080027
			public const int addEaten = 2131230759;
			
			// aapt resource value: 0x7f08002b
			public const int addPlan = 2131230763;
			
			// aapt resource value: 0x7f080006
			public const int burnTrackText = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int burnitemdatetime = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int burnitemname = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int burnitemtrack = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int burnlist = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int burnlisttitlename = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int burnlisttitletrack = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int burnpage = 2131230720;
			
			// aapt resource value: 0x7f08001b
			public const int delete = 2131230747;
			
			// aapt resource value: 0x7f08000a
			public const int dietitemdatetime = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int dietitemmetric = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int dietitemname = 2131230731;
			
			// aapt resource value: 0x7f080013
			public const int eatTrackText = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int eatitemdatetime = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int eatitemname = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int eatitemtrack = 2131230742;
			
			// aapt resource value: 0x7f080012
			public const int eatlist = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int eatlisttitlename = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int eatlisttitletrack = 2131230736;
			
			// aapt resource value: 0x7f08000d
			public const int eatpage = 2131230733;
			
			// aapt resource value: 0x7f08001c
			public const int edit = 2131230748;
			
			// aapt resource value: 0x7f08002a
			public const int editPlanEntry = 2131230762;
			
			// aapt resource value: 0x7f08001f
			public const int flb = 2131230751;
			
			// aapt resource value: 0x7f080002
			public const int flbBurn = 2131230722;
			
			// aapt resource value: 0x7f08000f
			public const int flpEat = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int frameLayout1 = 2131230734;
			
			// aapt resource value: 0x7f080001
			public const int frameLayout1burn = 2131230721;
			
			// aapt resource value: 0x7f080019
			public const int infolist = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int ll = 2131230746;
			
			// aapt resource value: 0x7f080025
			public const int manageBurns = 2131230757;
			
			// aapt resource value: 0x7f080028
			public const int manageFoods = 2131230760;
			
			// aapt resource value: 0x7f080021
			public const int name = 2131230753;
			
			// aapt resource value: 0x7f08001e
			public const int plan = 2131230750;
			
			// aapt resource value: 0x7f080020
			public const int planlist = 2131230752;
			
			// aapt resource value: 0x7f080023
			public const int removeBurnEntry = 2131230755;
			
			// aapt resource value: 0x7f080026
			public const int removeEatEntry = 2131230758;
			
			// aapt resource value: 0x7f080029
			public const int removePlanEntry = 2131230761;
			
			// aapt resource value: 0x7f080018
			public const int rl = 2131230744;
			
			// aapt resource value: 0x7f080017
			public const int value = 2131230743;
			
			// aapt resource value: 0x7f080022
			public const int values = 2131230754;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Burn = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BurnEntryLine = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DietInstanceLine = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Eat = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EatEntryLine = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int InfoComboVal = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ManageInfoLine = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ManageInfoView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Plan = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ValueRequests_DateTime = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ValueRequests_Double = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ValueRequests_InfoSelect = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ValueRequests_String = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int BurnEntryMenu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int BurnMenu = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int EatEntryMenu = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int EatMenu = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int PlanEntryMenu = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int PlanMenu = 2131165189;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int burn = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int eat = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int plan = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
